### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by CiaranG** [johanhil/copy-to-clipboard#2]
I know it seems silly for so few lines of code, but is there any chance you could release this under some license or other? Apache2, GPL, MIT, whatever?

**Comment by johanhil** [comment]
Sure thing. Which one do you prefer?

**Comment by CiaranG** [comment]
GPLv3 is my license of choice, but any of the above would be great.

**Comment by johanhil** [comment]
Alright, GPL it is. Thank you for taking interest in this project :-)
